FROM jenkins/slave

USER root

RUN curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

USER jenkins

ENTRYPOINT java -jar /usr/share/jenkins/slave.jar
